## 1. membuat tenor

In [29]:
import numpy as np

In [30]:
A = np.array([[23,50],[7,12]])
B = np.array([[57,67],[99,43]])
C = np.array([[75,21],[57,12]])
D = np.array([[87,26],[18,84]])

In [31]:
A

array([[23, 50],
       [ 7, 12]])

In [32]:
tensor = [A, B, C, D]
tensor = np.array(tensor)
tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [33]:
tensor.shape

(4, 2, 2)

## 2. perkalian matriks

In [34]:
A = np.array([[23,50,19],[7,12,109],[57,67,98]])
B = np.array([[17],[22],[19]])

In [35]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [36]:
A.shape

(3, 3)

In [37]:
B

array([[17],
       [22],
       [19]])

In [38]:
B.shape

(3, 1)

In [39]:
A @ B

array([[1852],
       [2454],
       [4305]])

## 3.Transpose, hitung determinan dan reverse

In [40]:
A = np.array([[23,50,19],[7,12,109],[57,67,98]])

In [41]:
A.T # membuat transpose

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [42]:
from numpy.linalg import det
A = np.array([[23,50,19],[7,12,109],[57,67,98]])

In [43]:
det(A)

131344.0000000002

In [44]:
from numpy.linalg import inv

In [45]:
A = np.array([[23,50,19],[7,12,109],[57,67,98]])

In [46]:
inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])